---
- name: Set up static networking configuration for the load balancers.
  hosts: all_components
  gather_facts: false
  become: true

  vars_files:
    - config.yml

  tasks:
    - name: Configure static IP address on each node.
      nmcli:
        conn_name: "Wired connection 1"
        ifname: eth0
        type: ethernet
        ip4: "{{ ipv4_subnet_prefix }}.{{ ip_host_octet }}/24"
        gw4: "{{ ipv4_subnet_prefix }}.1"
        dns4: "{{ ipv4_subnet_prefix }}.1"
        state: present
