---
- name: Add disk to Longhorn nodes
  hosts: longhorn_nodes
  become: true
  tasks:
    - parted:
        device: /dev/nvme0n1
        number: 1
        state: present

    - filesystem:
        fstype: ext4
        dev: /dev/nvme0n1
        state: present

    - mount:
        fstype: ext4
        src: /dev/nvme0n1
        path: /data
        state: mounted

    - name: Install open-iscsi
      ansible.builtin.apt:
        name: open-iscsi
        state: present

- name: Add disk to Longhorn nodes
  hosts: rk1_nodes_control_nodes
  become: true
  tasks:
    - name: Install open-iscsi
      ansible.builtin.apt:
        name: open-iscsi
        state: present
