---
- name: Install and Provision HAProxy and keepalived
  hosts: lb
  gather_facts: true
  become: true

  handlers:
    - name: restart-haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted
    - name: restart-keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted

  vars_files:
    - config.yml

  tasks:

    - name: Ensure required dependencies are installed.
      ansible.builtin.package:
        name:
          - haproxy
          - keepalived
        state: present
      become: true

    - name: 
      ansible.builtin.template:
        src: templates/lb/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        validate: haproxy -c -V -f %s
        backup: yes
      notify:
        - restart-haproxy
      become: true

    - name: 
      ansible.builtin.template:
        src: templates/lb/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        backup: yes
      notify:
        - restart-keepalived
      become: true
