---
- name: Set up cluster-wide configuration.
  hosts: cluster
  gather_facts: false
  become: true

  vars_files:
    - config.yml

  tasks:
    - name: Download K3s install script.
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: "~/k3s_install.sh"
        mode: a+x     
        force: yes 


- name: Upgrade the control plane.
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - config.yml

  tasks:
    - name: Install K3s on control plane (takes a while).
      ansible.builtin.shell: >-
        K3S_TOKEN="{{ lookup('community.general.onepassword', 'pi-cluster-k3s-token', field='credential', vault='Homelab') }}"
        INSTALL_K3S_EXEC="--disable traefik --tls-san {{ control_plane_vip }} --datastore-endpoint="mysql://{{ lookup('community.general.onepassword', 'pi-cluster-k3s-datastore', field='username', vault='Homelab') }}:{{ lookup('community.general.onepassword', 'pi-cluster-k3s-datastore', field='credential', vault='Homelab') }}@tcp\(nas-1.home.theberge.org:3307\)/k3s""
        INSTALL_K3S_VERSION="{{ kubernetes_cluster_version }}"
        ~/k3s_install.sh >> ~/k3s_install_log.txt
      args:
        chdir: "~"


- name: Upgrade the Worker Nodes
  hosts: nodes
  gather_facts: false
  serial: 1
  become: true

  vars_files:
    - config.yml

  tasks:
    - name: Install K3s on nodes (takes a while).
      ansible.builtin.shell: >-
        INSTALL_K3S_VERSION="{{ kubernetes_cluster_version }}"
        K3S_URL="{{ control_plane_api_url }}"
        K3S_TOKEN="{{ lookup('community.general.onepassword', 'pi-cluster-k3s-token', field='credential', vault='Homelab') }}"
        ~/k3s_install.sh >> ~/k3s_install_log.txt
