apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: argo-cd
    helm:
      values: |-
        redis-ha:
          enabled: true

        controller:
          replicas: 1

        server:
          replicas: 2

        repoServer:
          replicas: 2

        applicationSet:
          replicaCount: 2
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.6.12
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
