apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  destination:
    namespace: cloudflared
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/cloudflared
    repoURL: https://github.com/Encryptic/turing-pi
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
