apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
  - group: storage.k8s.io
    jsonPointers:
    - /spec/seLinuxMount
    kind: CSIDriver
    name: nfs.csi.k8s.io
  source:
    chart: csi-driver-nfs
    helm:
      parameters:
        - name: externalSnapshotter.enabled
          value: 'false'
    repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    targetRevision: v4.6.0
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
