apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb2
  namespace: argocd
spec:
  destination:
    namespace: influxdb2
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: influxdb2
    helm:
      valuesObject:
        nodeSelector:
          storage: "nvme"
        env:
          - name: INFLUXDB_DATA_WAL_FSYNC_DELAY
            value: 100ms
        resources:
          limits:
            cpu: 1
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 512Mi
        ## Create default user through docker entrypoint
        adminUser:
          organization: "influxdata"
          bucket: "default"
          user: "admin"
          retention_policy: "0s"
          password: ""
          token: ""
        ## Persist data to a persistent volume
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          size: 50Gi
          mountPath: /var/lib/influxdb2
          subPath: ""
        ## Pod disruption budget configuration
        pdb:
          ## Specifies whether a Pod disruption budget should be created
          create: true
          minAvailable: 1
    repoURL: https://helm.influxdata.com/
    targetRevision: 2.1.2
