apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.6.0
      helm:
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          longhornManager:
            nodeSelector:
              storage: "nvme"
          longhornDriver:
            nodeSelector:
              storage: "nvme"
          defaultSettings:
            defaultDataPath: "/data/longhorn"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
