apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.6.0 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          longhornManager:
            nodeSelector:
              label-storage: "label-nvme"
          longhornDriver:
            nodeSelector:
              label-storage: "label-nvme"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
