apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 5.4.0-weekly.288
    helm:
      values: |-
        runtimeConfig:
          ingester_limits: # limits that each ingester replica enforces
            max_ingestion_rate: 20000
            max_series: 1500000
            max_tenants: 1000
            max_inflight_push_requests: 30000
          distributor_limits: # limits that each distributor replica enforces
            max_ingestion_rate: 20000
            max_inflight_push_requests: 30000
            max_inflight_push_requests_bytes: 50000000
          overrides:
            anonymous:
              ingestion_tenant_shard_size: 9
              max_global_series_per_user: 1500000
              max_fetched_series_per_query: 100000
        minio:
          nodeSelector:
            storage: nvme
        alertmanager:
          nodeSelector:
            storage: nvme
        compactor:
          nodeSelector:
            storage: nvme
        ingester:
          persistentVolume:
            size: 25Gi
          zoneAwareReplication:
            zones:
              - name: zone-a
                nodeSelector:
                  storage: nvme
              - name: zone-b
                nodeSelector:
                  storage: nvme
              - name: zone-c
                nodeSelector:
                  storage: nvme
        store_gateway:
          zoneAwareReplication:
            zones:
              - name: zone-a
                nodeSelector:
                  storage: nvme
              - name: zone-b
                nodeSelector:
                  storage: nvme
              - name: zone-c
                nodeSelector:
                  storage: nvme            
    chart: mimir-distributed
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mimir
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
