apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: naglebot
  namespace: argocd
spec:
  destination:
    namespace: naglebot
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: git@github.com:Encryptic/naglebot.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
